parameters:
- name: jobName
  type: string
  default: BuildSqlDatabase
- name: dependsOn
  type: object
  default: []
- name: publishArtifact
  type: boolean
  default: false

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/database.csproj'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/src/database/bin/Release/netstandard2.1/'
      targetFolder: '$(Build.ArtifactStagingDirectory)/database'

  - publish: '$(Build.ArtifactStagingDirectory)/database'
    displayName: Publish database artifact
    artifact: database