parameters:
- name: jobName
  type: string
  default: BuildFunctionApp
- name: dependsOn
  type: object
  default: []
- name: publishArtifact
  type: boolean
  default: false

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    inputs:
      version: 6.0.x
      performMultiLevelLookup: true
      includePreviewVersions: true
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/function-app.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/function-app.csproj'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'

  - task: ArchiveFiles@2
    condition: and(succeeded(), eq('${{ parameters.publishArtifact }}', 'true'))
    displayName: "Package function-app to artifact staging directory"
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/src/function-app/bin/Release/net6.0/'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/function-app.zip'
      replaceExistingArchive: true

  - publish: $(Build.artifactStagingDirectory)/function-app.zip
    condition: and(succeeded(), eq('${{ parameters.publishArtifact }}', 'true'))
    displayName: Publish function-app artifact
    artifact: function-app