parameters:
- name: jobName
  type: string
  default: DeployFunctionApp
- name: dependsOn
  type: object
  default: []
- name: environmentServiceNameAzureRM

variables:
- name: function_app_name
  value: $[ dependencies.TerraformPlanAndApply.outputs['terraform_output.function_app_name'] ]

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  steps: 
    - download: current
      displayName: 'Download function-app artifact'
      artifact: function-app

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: '${{ parameters.environmentServiceNameAzureRM }}'
        appName: '$(function_app_name)'
        package: '$(Pipeline.Workspace)/function-app/function-app.zip'