parameters:
- name: workingDirectory
- name: backendServiceArm
- name: backendAzureRmResourceGroupName
- name: backendAzureRmStorageAccountName
- name: backendAzureRmContainerName
- name: backendAzureRmKey
- name: environmentServiceNameAzureRM
- name: varFile

stages:
- stage: DeployTerraform
  jobs:
  - job: DeployTerraform
    steps:
      - task: TerraformInstaller@0
        displayName: 'Terraform: Install'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Init'
        inputs:
          workingDirectory: '${{ parameters.workingDirectory }}'
          backendServiceArm: '${{ parameters.backendServiceArm }}'
          backendAzureRmResourceGroupName: '${{ parameters.backendAzureRmResourceGroupName }}'
          backendAzureRmStorageAccountName: '${{ parameters.backendAzureRmStorageAccountName }}'
          backendAzureRmContainerName: '${{ parameters.backendAzureRmContainerName }}'
          backendAzureRmKey: '${{ parameters.backendAzureRmKey }}'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Validate'
        inputs:
          command: validate
          workingDirectory: '${{ parameters.workingDirectory }}'
          commandOptions: '-var-file="${{ parameters.varFile }}"'
          environmentServiceNameAzureRM: '${{ parameters.environmentServiceNameAzureRM }}'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Plan'
        inputs:
          command: plan
          workingDirectory: '${{ parameters.workingDirectory }}'
          commandOptions: '-var-file="${{ parameters.varFile }}"'
          environmentServiceNameAzureRM: '${{ parameters.environmentServiceNameAzureRM }}'

      - task: TerraformTaskV2@2
        displayName: 'Terraform: Apply'
        inputs:
          command: apply
          workingDirectory: '${{ parameters.workingDirectory }}'
          commandOptions: '-var-file="${{ parameters.varFile }}"'
          environmentServiceNameAzureRM: '${{ parameters.environmentServiceNameAzureRM }}'