parameters:
- name: workingDirectory
- name: backendServiceArm
- name: backendAzureRmResourceGroupName
- name: backendAzureRmStorageAccountName
- name: backendAzureRmContainerName
- name: backendAzureRmKey
- name: environmentServiceNameAzureRM
- name: varFile

stages:
- stage: Terraform_Validate
  jobs:

  - job:
    steps:
      - task: TerraformInstaller@0

      - task: TerraformTaskV1@0
        displayName: 'Terraform: Init'
        inputs:
          workingDirectory: parameters.workingDirectory
          backendServiceArm: parameters.backendServiceArm
          backendAzureRmResourceGroupName: parameters.backendAzureRmResourceGroupName
          backendAzureRmStorageAccountName: parameters.backendAzureRmStorageAccountName
          backendAzureRmContainerName: parameters.backendAzureRmContainerName
          backendAzureRmKey: parameters.backendAzureRmKey

      - task: TerraformTaskV1@0
        displayName: 'Terraform: Validate'
        inputs:
          command: plan
          workingDirectory: parameters.workingDirectory
          commandOptions: '-var-file="${{ parameters.varFile }}"'
          environmentServiceNameAzureRM: parameters.environmentServiceNameAzureRM

      - task: TerraformTaskV1@0
        displayName: 'Terraform: Plan'
        inputs:
          command: plan
          workingDirectory: parameters.workingDirectory
          commandOptions: '-var-file="${{ parameters.varFile }}"'
          environmentServiceNameAzureRM: parameters.environmentServiceNameAzureRM